config/routes.rb
Rails.application.routes.draw do
  post 'image/img_upload'

  root to: 'home#index'

  get 'home/index'
  resources :orders
  resources :users
  resources :sessions
  get 'logout', to: 'sessions#destroy', as: 'logout'

  get '/download' => 'products#download'
  resources :products do
    collection { post :import}
  end

  post 'home/upload' => 'home#upload'
  post '/seed' => 'home#seed'
  get 'home/admin'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :order
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :products
  has_many :images

  # for updating, downloading csv
  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |product|
        csv << product.attributes.values_at(*column_names)
      end
    end
  end

end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :order

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |product|
        csv << product.attributes.values_at(*column_names)
      end
    end
  end

  def self.import(file)
    CSV.foreach(file.path, headers:true) do |row|
      Product.create! row.to_hash
    end
  end


end

app/models/user.rb
class User < ApplicationRecord
  has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  @@img_url = nil

  def index
  end

  def upload
    if params[:img].has_key?
      uploader = ImgUploader.new
      uploader.store!(params[:img])
      @@img_url = uploader.url
    end
  end

  def seed
    Rails.application.load_seed
  end
end

app/controllers/image_controller.rb
class ImageController < ApplicationController
  # $이거 붙이면 전역변수됨 ㅇㅇ
  $img_url = nil

  def img_upload
    uploader = ImgUploader.new
    uploader.store!(params[:img])
    Image.create(url: uploader.url, date: Date.today, order_id: 1)
    $img_url = uploader.url
    redirect_to root_path
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = Order.where(user_id: current_user.id)
  end

  def show
    @products = Order.find(params[:id]).products
    respond_to do |format|
      format.html
      # format.csv { render text: @products.to_csv} # render at page
      format.csv { send_data @products.to_csv, filename: 'tm_tweet_0814.csv'}
      format.xls # { send_data @products.to_csv(col_sep: "\t") }
    end
  end

  def new
    @order = Order.new
  end

  def create
    order = Order.new(order_params)
    order.user = current_user
    order.save
    redirect_to orders_path
  end

  def import
    Product.import(params[:file])
    redirect_to root_url, notice: "Products imported."
  end


  private

  def order_params
    params.require(:order).permit(:user_id, :length, :navercafe, :dcinside, :twitter, :keyword)
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.order(:id)
  end

  def show
    @products = Product.order(:id)
  end

  def import
    Product.import(params[:file])
    redirect_to root_url, notice: "Products imported."
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && User.find_by_password(params[:password])
      session[:user_id] = user.id
      redirect_to "/"
    else
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to "/"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.save
      redirect_to "/"
    else
      redirect_to :back
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/image_helper.rb
module ImageHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/admin.html.erb
<br><br><br><br><br>
<%= button_to "seed", seed_path %>


<!--<form action="/home/upload" method="post" enctype="multipart/form-data">-->
<!--<div class="form-group">-->
<!--<label for="exampleInputFile">File input</label>-->
<!--<input type="file" id="exampleInputFile" name="img">-->
<!--<p class="help-block">Example block-level help text here.</p>-->
<!--</div>-->
<!--<button type="submit" class="btn btn-default">Submit</button>-->
<!--</form>-->
<!--<% unless $img_url.nil? %>-->
    <!--<img src="<%= $img_url %>">-->
    <!--<% end %>-->

app/views/home/index.html.erb
<div id="particles-js"></div>

<div class="banner">
  <h1 class="banner-main-title">Be Omniscient with Omnisian</h1>
  <p class="banner-sub-title">We provide daily keyword for your business !</p>
  <p class="banner-sub-title">We provide visual trend for your business !</p>
  <p class="banner-sub-title">커뮤니티 키워드 분석 서비스</p>
  <p class="banner-content">1. 오늘의 키워드 추출</p>
  <p class="banner-content">2. 의미있는 게시글 추천</p>
  <p class="banner-content">3. 커뮤니티 데이터 변화량 시각화 자료 제공</p>
  <p class="banner-content">4. 상세한 분석을 위한 로우 데이터 제공</p>
  <p class="banner-content">5. 경쟁사 커뮤니티 모니터링</p>
</div>
<div class = "contact-banner">
  <h2>Contact Us</h2>
  <p>주 | OMNISIAN</p>
  <p>010-7979-8334</p>
  <p>서울특별시 성동구 마조로 12길 12-2</p>
</div>

<%= javascript_include_tag("particles.min.js") %>
<%= javascript_include_tag("index.js") %>

app/views/image/img_upload.html.erb
<h1>Image#img_upload</h1>
<p>Find me in app/views/image/img_upload.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Omnisian</title>
  <%= csrf_meta_tags %>
  <!-- Latest compiled and minified CSS -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>    <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
  <meta name="viewport" content="width=device-width, user-scalable=no">

  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
</head>

<body>
<header>
  <nav class="navbar navbar-expand-lg navbar-light fixed-top custom-nav-attr">
    <div class="container">
      <a class="navbar-brand active" href="/">OMNISIAN</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav custom-navbar-nav-attr">
          <% if current_user %>
              <a class="nav-item nav-link custom-nav-item-attr" href="/orders/new">주문하기</a>
              <a class="nav-item nav-link custom-nav-item-attr" href="/orders">주문내역</a>
              <a class="nav-item nav-link custom-nav-item-attr" href="/logout">로그아웃</a>
          <% else %>
              <a class="nav-item nav-link custom-nav-item-attr" href="/sessions/new">로그인</a>
          <% end %>
        </div>
      </div>
    </div>
  </nav>
</header>
<%= yield %>
</body>
</html>

app/views/orders/_graph.html.erb
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.css">
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.min.js"></script>

<div>
  <p class="sub-small-title">오늘의 키워드 [2017-08-14, 410]</p>
  <%= content_tag :div, '', id: 'todays_keyword' %>
</div>

<div class="graph-div">
  <p class="sub-small-title">데이터 변화량</p>
  <%= content_tag :div, '', id: 'products_chart' %>
</div>

<script>
  new Morris.Line({
    // ID of the element in which to draw the chart.
    element: 'products_chart',
    // Chart data records -- each entry in this array corresponds to a point on
    // the chart.
    data: [
      { date: '2017-07-11', total:234},
      { date: '2017-07-12', total:401},
      { date: '2017-07-13', total:603},
      { date: '2017-07-14', total:201},
      { date: '2017-07-15', total:351},
      { date: '2017-07-16', total:701},
      { date: '2017-07-17', total:8541},
      { date: '2017-07-18', total:901},
      { date: '2017-07-19', total:821},
      { date: '2017-07-20', total:943},
      { date: '2017-07-21', total:677},
      { date: '2017-07-22', total:678},
      { date: '2017-07-23', total:473},
      { date: '2017-07-24', total:571},
      { date: '2017-07-25', total:474},
      { date: '2017-07-26', total:301},
      { date: '2017-07-27', total:337},
      { date: '2017-07-28', total:301},
      { date: '2017-07-29', total:603},
      { date: '2017-07-30', total:1001},
      { date: '2017-07-31', total:533},
      { date: '2017-08-01', total:531},
      { date: '2017-08-02', total:445},
      { date: '2017-08-03', total:505},
      { date: '2017-08-04', total:283},
      { date: '2017-08-05', total:1301},
      { date: '2017-08-06', total:901},
      { date: '2017-08-07', total:332},
      { date: '2017-08-08', total:305},
      { date: '2017-08-09', total:441},
      { date: '2017-08-10', total:523},
      { date: '2017-08-11', total:301},
      { date: '2017-08-12', total:501},
      { date: '2017-08-13', total:301},
      { date: '2017-08-14', total:411},
    ],
    // The name of the data record attribute that contains x-values.
    xkey: ['date'],
    // A list of names of data record attributes that contain y-values.
    ykeys: ['total'],
    // Labels for the ykeys -- will be displayed when you hover over the
    // chart.
    labels: ['total'],

    hoverCallback: ['title'],
  });

  new Morris.Bar({
    element: 'todays_keyword',
    data: [
      { keyword: '하이트', a:21, b: (21/410)*100},
      { keyword: '케이스위스', a:17, b: (17/410)*100},
      { keyword: '렌즈나인', a:16, b: (16/410)*100},
      { keyword: '멕시카나', a:15, b: (15/410)*100},
      { keyword: '이니스프리', a:15, b: (15/410)*100},
      { keyword: '스노우', a:14, b: (14/410)*100},
      { keyword: '화장품', a:14, b:  (14/410)*100},
      { keyword: '교복', a:14, b: (14/410)*100},
      { keyword: '삼성페이', a:13, b: (13/410)*100},
      { keyword: '상어', a:8, b: (8/410)*100},
      { keyword: '에너제틱', a:8, b: (8/410)*100},
    ],
    xkey: 'keyword',
    ykeys: ['a', 'b'],
    labels: ['count', 'percentage']
  });
</script>

app/views/orders/_import.html.erb
<!--<h2>Import Document</h2>-->

<!--<%= form_tag import_products_path, multipart: true do %>-->
    <!--<%= file_field_tag :file %>-->
    <!--<%= submit_tag "Import" %>-->
<!--<% end %>-->
<!--<br>-->
<!--<br>-->

app/views/orders/_raw.html.erb
<div class="graph-div">
  <p class="sub-small-title">RAW DATA(<%= link_to "Excel Download Link", products_path(format: "xls") %>)</p>
  <table class="table" id="products">
    <thead class="thead-inverse">
      <tr>
        <th>date</th>
        <th>content</th>
        <th>username</th>
      </tr>
    </thead>
    <tbody>
      <% @products.each do |product| %>
        <tr>
          <td><%= product.date %></td>
          <td><%= product.content %></td>
          <td><%= product.username %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/orders/index.html.erb
<div id="particles-js"></div>

<div class="orders-div">
  <div class="orders-inside-div">
    <div class="orders-content-div">
      <p class="sub-small-title">Your Orders</p>
      <table class="table" id="products">
        <thead class="thead-inverse">
          <tr>
            <th>키워드</th>
            <th>기간</th>
            <th>구매시간</th>
            <th>링크</th>
          </tr>
        </thead>
        <tbody>
          <% @orders.each do |o| %>
            <tr>
              <td><%= o.keyword %></td>
              <td>
                <% if o.length == 1 %>
                  체험판
                <% elsif o.length == 2 %>
                  1달
                <% elsif o.length == 2 %>
                  3달
                <% else %>
                  6달
                <% end %>
              </td>
              <td>2017-08-13</td>
              <td><%= link_to '링크', (order_path(o.id)) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<%= javascript_include_tag("particles.min.js") %>
<%= javascript_include_tag("index.js") %>

app/views/orders/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
          xmlns:o="urn:schemas-microsoft-com:office:office"
          xmlns:x="urn:schemas-microsoft-com:office:excel"
          xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
          xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">id</Data></Cell>
        <Cell><Data ss:Type="String">title</Data></Cell>
        <Cell><Data ss:Type="String">content</Data></Cell>
        <Cell><Data ss:Type="String">Price</Data></Cell>
      </Row>
      <% @products.each do |product| %>
          <Row>
            <Cell><Data ss:Type="Number"><%= product.id %></Data></Cell>
            <Cell><Data ss:Type="String"><%= product.title %></Data></Cell>
            <Cell><Data ss:Type="Number"><%= product.content %></Data></Cell>
          </Row>
      <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/orders/new.html.erb
<div id="particles-js"></div>
<div class="banner orders-new-banner">
  <div class="banner-card">
    <h1 class="orders-title">주문하기</h1>
    <%= form_for @order do |f| %>
      <div class="orders-ques-div">
        <span class="ques-title">기간 선택 | </span>
        <div class="form-check form-check-inline">
          <label class="form-check-label">
            <%= f.radio_button :length, 1, class: "form-check-input" %> 체험판
          </label>
        </div>
        <div class="form-check form-check-inline">
          <label class="form-check-label">
            <%= f.radio_button :length, 2, class: "form-check-input" %> 1달
          </label>
        </div>
        <div class="form-check form-check-inline">
          <label class="form-check-label" >
            <%= f.radio_button :length, 3, class: "form-check-input" %> 3달
          </label>
        </div>
        <div class="form-check form-check-inline">
          <label class="form-check-label" >
            <%= f.radio_button :length, 4, class: "form-check-input"%> 6달
          </label>
        </div>
      </div>
      <div class="orders-ques-div">
        <span class="ques-title">사이트 선택 | </span>
        <div class="form-check form-check-inline">
          <label class="form-check-label" >
            <%= f.check_box :navercafe, class: "form-check-input" %> 네이버 카페
          </label>
        </div>
        <div class="form-check form-check-inline">
          <label class="form-check-label" >
            <%= f.check_box :dcinside, class: "form-check-input" %> 디씨인사이드
          </label>
        </div>
        <div class="form-check form-check-inline">
          <label class="form-check-label" >
            <%= f.check_box :twitter, class: "form-check-input" %> 트위터
          </label>
        </div>
      </div>
      <div class="form-group row orders-ques-div">
        <label class="col-sm-2 col-form-label">키워드 | </label>
        <div class="col-sm-10">
          <%= f.text_field :keyword, rows: 1, class: "form-control custom-input"%>
        </div>
      </div>
      <div class="form-group ques-submit-div">
        <%= f.submit ("신청하기"), class: "btn btn-outline-primary" %>
      </div>
    <% end %>
  </div>
</div>
<%= javascript_include_tag("particles.min.js") %>
<%= javascript_include_tag("index.js") %>

app/views/orders/show.html.erb
<div class="mypage-div">
  <%= render 'import' %>
  <%= render 'graph' %>
  <br>
  <%= render 'raw' %>
</div>

app/views/products/_graph.html.erb
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.css">
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.min.js"></script>

<%= content_tag :div, '', id: 'products_chart', data: {products: @products} %>

<table id="products">
  <tr>
    <th>date</th>
    <th>title</th>
    <th>content</th>
  </tr>
  <% @products.each do |product| %>
      <tr>
        <td><%= product.date %></td>
        <td><%= product.title %></td>
        <td><%= product.content %></td>
      </tr>
  <% end %>
</table>

<script>
  new Morris.Line({
    // ID of the element in which to draw the chart.
    element: 'products_chart',
    // Chart data records -- each entry in this array corresponds to a point on
    // the chart.
    data: $('#products_chart').data('products'),
    // The name of the data record attribute that contains x-values.
    xkey: ['released_on'],
    // A list of names of data record attributes that contain y-values.
    ykeys: ['fweek', 'expectation', 'percent_error', 'preview'],
    // Labels for the ykeys -- will be displayed when you hover over the
    // chart.
    labels: ['  first week audience','expectation', 'percent_error', 'preview'],

    hoverCallback: ['title_en'],
  });
</script>

app/views/products/index.html.erb
<br>
Mypage
<br>
<% @orders.each do |o| %>
    purchased at <%= o.created_at %><br>
    <%= o.products.each do |p| %>

    <% end %>
<% end %>


<%= render 'import' %>
<%= render 'download' %>
<%= render 'graph' %>

app/views/products/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
          xmlns:o="urn:schemas-microsoft-com:office:office"
          xmlns:x="urn:schemas-microsoft-com:office:excel"
          xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
          xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">id</Data></Cell>
        <Cell><Data ss:Type="String">name</Data></Cell>
        <Cell><Data ss:Type="String">date</Data></Cell>
        <Cell><Data ss:Type="String">title</Data></Cell>
        <Cell><Data ss:Type="String">content</Data></Cell>
        <Cell><Data ss:Type="String">username</Data></Cell>
        <Cell><Data ss:Type="String">index</Data></Cell>
        <Cell><Data ss:Type="String">category</Data></Cell>
        <Cell><Data ss:Type="String">reply_count</Data></Cell>
        <Cell><Data ss:Type="String">view_count</Data></Cell>
        <Cell><Data ss:Type="String">like_count</Data></Cell>
        <Cell><Data ss:Type="String">link</Data></Cell>
      </Row>
      <% @products.each do |product| %>
          <Row>
            <Cell><Data ss:Type="Number"><%= product.id %></Data></Cell>
            <Cell><Data ss:Type="String"><%= product.name %></Data></Cell>
            <Cell><Data ss:Type="String"><%= product.date %></Data></Cell>
            <Cell><Data ss:Type="String"><%= product.title %></Data></Cell>
            <Cell><Data ss:Type="String"><%= product.content %></Data></Cell>
            <Cell><Data ss:Type="String"><%= product.username %></Data></Cell>
            <Cell><Data ss:Type="Number"><%= product.index %></Data></Cell>
            <Cell><Data ss:Type="String"><%= product.category %></Data></Cell>
            <Cell><Data ss:Type="Number"><%= product.reply_count %></Data></Cell>
            <Cell><Data ss:Type="Number"><%= product.view_count %></Data></Cell>
            <Cell><Data ss:Type="Number"><%= product.like_count %></Data></Cell>
            <Cell><Data ss:Type="String"><%= product.link %></Data></Cell>
          </Row>
      <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

<%= form_for @user do |f| %>

    <%= f.email_field :email, autofocus: true, placeholder: "email" %> <br>

    <%= f.password_field :password, autocomplete: "off", placeholder: "password" %> <br>

    <%= f.submit "Sign Up" %> <br>

<% end %>